package entity;

// Generated Sep 5, 2016 1:22:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StockCategoryId generated by hbm2java
 */
@Embeddable
public class StockCategoryId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int stockId;
	private int categoryId;
	private Date createdDate;
	private String createBy;

	public StockCategoryId() {
	}

	public StockCategoryId(int stockId, int categoryId) {
		this.stockId = stockId;
		this.categoryId = categoryId;
	}

	public StockCategoryId(int stockId, int categoryId, Date createdDate,
			String createBy) {
		this.stockId = stockId;
		this.categoryId = categoryId;
		this.createdDate = createdDate;
		this.createBy = createBy;
	}

	@Column(name = "stock_id", nullable = false)
	public int getStockId() {
		return this.stockId;
	}

	public void setStockId(int stockId) {
		this.stockId = stockId;
	}

	@Column(name = "category_id", nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "create_by", length = 10)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StockCategoryId))
			return false;
		StockCategoryId castOther = (StockCategoryId) other;

		return (this.getStockId() == castOther.getStockId())
				&& (this.getCategoryId() == castOther.getCategoryId())
				&& ((this.getCreatedDate() == castOther.getCreatedDate()) || (this
						.getCreatedDate() != null
						&& castOther.getCreatedDate() != null && this
						.getCreatedDate().equals(castOther.getCreatedDate())))
				&& ((this.getCreateBy() == castOther.getCreateBy()) || (this
						.getCreateBy() != null
						&& castOther.getCreateBy() != null && this
						.getCreateBy().equals(castOther.getCreateBy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStockId();
		result = 37 * result + this.getCategoryId();
		result = 37
				* result
				+ (getCreatedDate() == null ? 0 : this.getCreatedDate()
						.hashCode());
		result = 37 * result
				+ (getCreateBy() == null ? 0 : this.getCreateBy().hashCode());
		return result;
	}

}
