---
server:
  port: 8080
  contextPath: /SpringBootCRUDApp
---
#fix error: hibernate dialect: org.hibernate.dialect.MySQLInnoDBDialect
#set profiles local
spring:
  profiles: local,default
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/websystique
    username: root
    password: khoivu2206
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
#      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLInnoDBDialect

