package entity;

// Generated Sep 5, 2016 1:22:02 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StockCategory generated by hbm2java
 */
@Entity
@Table(name = "stock_category", catalog = "manytomanydb")
public class StockCategory implements java.io.Serializable {

	private StockCategoryId id;
	private Stock stock;
	private Category category;

	public StockCategory() {
	}

	public StockCategory(StockCategoryId id, Stock stock, Category category) {
		this.id = id;
		this.stock = stock;
		this.category = category;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "stockId", column = @Column(name = "stock_id", nullable = false)),
			@AttributeOverride(name = "categoryId", column = @Column(name = "category_id", nullable = false)),
			@AttributeOverride(name = "createdDate", column = @Column(name = "created_date", length = 10)),
			@AttributeOverride(name = "createBy", column = @Column(name = "create_by", length = 10)) })
	public StockCategoryId getId() {
		return this.id;
	}

	public void setId(StockCategoryId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stock_id", nullable = false, insertable = false, updatable = false)
	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false, insertable = false, updatable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

}
